Config = {}

Config.SkinDistance = 10

Config.AnimalList = {
    [989669666]   = { name = "Rat", givenItem = { "h_small_animal" }, givenAmount = { 1 } },
    [-1797625440] = { name = "Armadillo", givenItem = { "h_small_pelt", "h_meat_small_game" }, givenAmount = { 1, {1, 2, 3} } },
    [-1170118274] = { name = "American Badger", givenItem = { "h_small_pelt", "h_meat_small_game" }, givenAmount = { 1, {1, 2, 3} } },
    [1755643085]  = { name = "American Pronghorn Doe", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart" }, givenAmount = { 1, {1, 2, 3}, 1 } },
    [-1124266369] = { name = "Bear", givenItem = { "h_large_pelt", "h_meat_big_game", "h_animal_heart", "h_animal_fat", "h_animal_trophy" }, givenAmount = { 1, {2, 4, 6}, 1, {2, 3, 4}, 1 } },
    [-1568716381] = { name = "Big Horn Ram", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart", "h_animal_trophy" }, givenAmount = { 1, {1, 2, 3}, 1, 1 } },
    [-1963605336] = { name = "Buck", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart", "h_animal_trophy" }, givenAmount = { 1, {1, 2, 3}, 1, 1 } },
    [1556473961]  = { name = "Bison", givenItem = { "h_large_pelt", "h_meat_big_game", "h_animal_heart", "h_animal_trophy" }, givenAmount = { 1, {2,4,6}, 1, 1 } },
    [367637652]   = { name = "Bison", givenItem = { "h_large_pelt", "h_meat_big_game", "h_animal_heart", "h_animal_trophy" }, givenAmount = { 1, {2,4,6}, 1, 1 } },
    [1957001316]  = { name = "Bull", givenItem = { "h_large_pelt", "h_meat_big_game", "h_animal_heart", "h_animal_trophy" }, givenAmount = { 1, {2, 3, 5}, 1, 1 } },
    [1110710183]  = { name = "Deer", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart" }, givenAmount = { 1, {1,2,3}, 1 } },
    [-1003616053] = { name = "Duck", givenItem = { "h_feather", "h_meat_bird", "h_animal_fat" }, givenAmount = { {1, 2, 3}, {1, 1, 2}, {1, 1, 2} } },
    [1459778951]  = { name = "Eagle", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { {1, 2, 3}, {1, 1, 2} } },
    [831859211]   = { name = "Egret", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { {1, 2, 3}, {1, 1, 2} } },
    [252669332]   = { name = "American Red Fox", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart" }, givenAmount = { 1, {1, 2, 3}, 1 } },
    [-1143398950] = { name = "Big Grey Wolf", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart", "h_animal_trophy" }, givenAmount = { 1, {1, 2, 3}, 1, 1 } },
    [-885451903]  = { name = "Medium Grey Wolf", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart", "h_animal_trophy" }, givenAmount = { 1, {1, 2, 3}, 1, 1 } },
    [-829273561]  = { name = "Small Grey Wolf", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_trophy" }, givenAmount = { 1, {1, 2, 3}, 1 } },
    [1104697660]  = { name = "Vulture", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-407730502]  = { name = "Snapping Turtle", givenItem = { "h_turtle_shell", "h_meat_reptile" }, givenAmount = { 1, 2 } },
    [-466054788]  = { name = "Wild Turkey", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-2011226991] = { name = "Wild Turkey", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-166054593]  = { name = "Wild Turkey", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-22968827]   = { name = "Water Snake", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [-229688157]  = { name = "CottonMouth Water Snake", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [-1790499186] = { name = "Snake Red Boa", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [1464167925]  = { name = "Snake Fer-De-Lance", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [846659001]   = { name = "Black-Tailed Rattlesnake", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [545068538]   = { name = "Western Rattlesnake", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [-121266332]  = { name = "Striped Skunk", givenItem = { "h_small_pelt", "h_meat_small_game" }, givenAmount = { 1, 1 } },
    [-1211566332] = { name = "Striped Skunk", givenItem = { "h_small_pelt", "h_meat_small_game" }, givenAmount = { 1, 1 } },
    [40345436]    = { name = "Merino Sheep", givenItem = { "h_wool", "h_meat_mutton", "h_animal_heart" }, givenAmount = { 1, 2, 1 } },
    [-164963696]  = { name = "Herring Seagull", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-1076508705] = { name = "Roseate Spoonbill", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [2023522846]  = { name = "Dominique Rooster", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-466687768]  = { name = "Red-Footed Booby", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-575340245]  = { name = "Wester Raven", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [1458540991]  = { name = "North American Racoon", givenItem = { "h_small_pelt", "h_meat_small_game" }, givenAmount = { 1, 1 } },
    [-541762431]  = { name = "Black-Tailed Jackrabbit", givenItem = { "h_small_pelt", "h_meat_small_game" }, givenAmount = { 1, 1 } },
    [2079703102]  = { name = "Greater Prairie Chicken", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-1414989025] = { name = "Wirginia Possum", givenItem = { "h_small_pelt", "h_meat_small_game" }, givenAmount = { 1, 1 } },
    [1007418994]  = { name = "Berkshire Pig", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart", "h_animal_fat" }, givenAmount = { 1, 2, 1, 4 } },
    [1416324601]  = { name = "Ring-Necked Pheasant", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [1265966684]  = { name = "American White Pelican", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-1797450568] = { name = "Blue And Yellow Macaw", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [1654513481]  = { name = "Panther", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart", "h_animal_trophy" }, givenAmount = { 1, 2, 1, 1 } },
    [120598262]   = { name = "Californian Condor", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-2063183075] = { name = "Dominique Chicken", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-2073130256] = { name = "Double-Crested Cormorant", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [90264823]    = { name = "Cougar", givenItem = { "h_large_pelt", "h_meat_big_game", "h_animal_heart", "h_animal_trophy" }, givenAmount = { 1, {2, 3, 5}, 1, 1 } },
    [-50684386]   = { name = "Florida Cracker Cow", givenItem = { "h_large_pelt", "h_meat_big_game", "h_animal_heart" }, givenAmount = { 1, {2, 3, 5}, 1 } },
    [480688259]   = { name = "Coyote", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart" }, givenAmount = { 1, {1, 2, 3}, 1 } },
    [-564099192]  = { name = "Whooping Crane", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [45741642]    = { name = "Gila Monster", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [-753902995]  = { name = "Alpine Goat", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart" }, givenAmount = { 1, 2, 1 } },
    [723190474]   = { name = "Canada Goose", givenItem = { "h_feather", "h_meat_bird", "h_animal_fat" }, givenAmount = { 1, 1, 1 } },
    [-2145890973] = { name = "Ferruinous Hawk", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [1095117488]  = { name = "Great Blue Heron", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-1854059305] = { name = "Green Iguana", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [-593056309]  = { name = "Desert Iguana", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [1751700893]  = { name = "Peccary Pig", givenItem = { "h_medium_pelt", "h_meat_game", "h_animal_heart", "h_animal_fat" }, givenAmount = { 1, 2, 1, 4 } },
    [386506078]   = { name = "Common Loon", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [-1098441944] = { name = "Moose", givenItem = { "h_large_pelt", "h_meat_big_game", "h_animal_heart", "h_animal_trophy" }, givenAmount = { 1, 3, 1, 1 } },
    [-1134449699] = { name = "American Muskrat", givenItem = { "h_small_pelt", "h_meat_small_game" }, givenAmount = { 1, 1 } },
    [-86244272]   = { name = "Great Horned Owl", givenItem = { "h_feather", "h_meat_bird" }, givenAmount = { 1, 1 } },
    [556355544]   = { name = "Angus Ox", givenItem = { "h_large_pelt", "h_meat_big_game", "h_animal_heart" }, givenAmount = { 1, 3, 1 } },
    [-1892280447] = { name = "Alligator Small", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [-2004866590] = { name = "Alligator", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [-1295720802] = { name = "Northen American Alligator", givenItem = { "h_reptile_skin", "h_meat_reptile" }, givenAmount = { 1, 1 } },
    [759906147]   = { name = "North American Beaver", givenItem = { "h_small_pelt", "h_meat_small_game" }, givenAmount = { 1, 1 } },
    [730092646]   = { name = "American Black Bear", givenItem = { "h_large_pelt", "h_meat_big_game", "h_animal_heart", "h_animal_fat", "h_animal_trophy" }, givenAmount = { 1, 3, 1, 3, 1 } }
}
