-- Hunting shop, buys only
    ['butcher'] = {
        -- Meats, trophies, and other parts
        { name = 'h_feather', amount = 0, buyPrice = string.format("%.2f", 0.05) },
        { name = 'h_meat_reptile', amount = 0, buyPrice = string.format("%.2f", 0.50) },
        { name = 'h_meat_bird', amount = 0, buyPrice = string.format("%.2f", 0.50) },
        { name = 'h_meat_small_game', amount = 0, buyPrice = string.format("%.2f", 0.75) },
        { name = 'h_meat_game', amount = 0, buyPrice = string.format("%.2f", 1.25) },
        { name = 'h_meat_big_game', amount = 0, buyPrice = string.format("%.2f", 1.50) },
        { name = 'h_meat_mutton', amount = 0, buyPrice = string.format("%.2f", 2.00) },
        { name = 'h_animal_fat', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_animal_heart', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_claw_animal', amount = 0, buyPrice = string.format("%.2f", 2.00) },
        { name = 'h_antler_buck', amount = 0, buyPrice = string.format("%.2f", 2.00) },
        { name = 'h_antler_elk', amount = 0, buyPrice = string.format("%.2f", 2.50) },
        { name = 'h_antler_moose', amount = 0, buyPrice = string.format("%.2f", 2.50) },
        { name = 'h_horn_animal', amount = 0, buyPrice = string.format("%.2f", 2.00) },
        { name = 'h_tusk_boar', amount = 0, buyPrice = string.format("%.2f", 2.00) },
        { name = 'h_wool', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_small_animal', amount = 0, buyPrice = string.format("%.2f", 1.00) },

        -- Pelts, hides, and skins
        { name = 'h_hide_cow', amount = 0, buyPrice = string.format("%.2f", 2.50) },
        { name = 'h_pelt_badger', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_pelt_beaver', amount = 0, buyPrice = string.format("%.2f", 1.50) },
        { name = 'h_pelt_coyote', amount = 0, buyPrice = string.format("%.2f", 1.50) },
        { name = 'h_pelt_fox', amount = 0, buyPrice = string.format("%.2f", 1.50) },
        { name = 'h_pelt_muskrat', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_pelt_opossum', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_pelt_rabbit', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_pelt_raccoon', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_pelt_skunk', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_pelt_wolf', amount = 0, buyPrice = string.format("%.2f", 2.50) },
        { name = 'h_skin_alligator', amount = 0, buyPrice = string.format("%.2f", 5.00) },
        { name = 'h_skin_armadillo', amount = 0, buyPrice = string.format("%.2f", 1.00) },
        { name = 'h_skin_bear', amount = 0, buyPrice = string.format("%.2f", 7.50) },
        { name = 'h_skin_buck', amount = 0, buyPrice = string.format("%.2f", 6.00) },
        { name = 'h_skin_buffalo', amount = 0, buyPrice = string.format("%.2f", 7.50) },
        { name = 'h_skin_cougar', amount = 0, buyPrice = string.format("%.2f", 7.50) },
        { name = 'h_skin_deer', amount = 0, buyPrice = string.format("%.2f", 5.00) },
        { name = 'h_skin_iguana', amount = 0, buyPrice = string.format("%.2f", 2.00) },
        { name = 'h_skin_elk', amount = 0, buyPrice = string.format("%.2f", 7.50) },
        { name = 'h_skin_goat', amount = 0, buyPrice = string.format("%.2f", 4.00) },
        { name = 'h_skin_javelina_boar', amount = 0, buyPrice = string.format("%.2f", 5.00) },
        { name = 'h_skin_moose', amount = 0, buyPrice = string.format("%.2f", 9.00) },
        { name = 'h_skin_panther', amount = 0, buyPrice = string.format("%.2f", 9.00) },
        { name = 'h_skin_pig', amount = 0, buyPrice = string.format("%.2f", 5.00) },
        { name = 'h_skin_pronghorn', amount = 0, buyPrice = string.format("%.2f", 5.00) },
        { name = 'h_skin_ram', amount = 0, buyPrice = string.format("%.2f", 6.00) },
        { name = 'h_snake_skin', amount = 0, buyPrice = string.format("%.2f", 1.50) },

        -- Legendary pelts
        { name = 'h_pelt_beaver_legendary', amount = 0, buyPrice = string.format("%.2f", 25.00) },
        { name = 'h_pelt_coyote_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_pelt_fox_legendary', amount = 0, buyPrice = string.format("%.2f", 75.00) },
        { name = 'h_pelt_wolf_legendary', amount = 0, buyPrice = string.format("%.2f", 100.00) },

        -- Legendary skins
        { name = 'h_skin_alligator_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_skin_bear_grizzly_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_skin_buck_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_skin_buffalo_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_skin_cougar_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_skin_elk_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_skin_javelina_boar_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_skin_moose_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_skin_panther_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        { name = 'h_skin_ram_legendary', amount = 0, buyPrice = string.format("%.2f", 50.00) },
        
    },
